const EN = {
  0: ['', ''],
  1: ['first', 'one'],
  2: ['second', 'two'],
  3: ['third', 'three'],
  4: ['fourth', 'four'],
  5: ['fifth', 'five'],
  6: ['sixth', 'six'],
  7: ['seventh', 'seven'],
  8: ['eighth', 'eight'],
  9: ['ninth', 'nine'],
  10: ['tenth', 'ten'],
  11: ['eleventh', 'eleven'],
  12: ['twelfth', 'twelve'],
  13: ['thirteenth', 'thirteen'],
  14: ['fourteenth', 'fourteen'],
  15: ['fifteenth', 'fifteen'],
  16: ['sixteenth', 'sixteen'],
  17: ['seventeenth', 'seventeen'],
  18: ['eighteenth', 'eighteen'],
  19: ['nineteenth', 'nineteen'],
  20: ['twentieth', 'twenty'],
  30: ['thirtieth', 'thirty'],
  40: ['fortieth', 'forty'],
  50: ['fiftieth', 'fifty'],
  60: ['sixtieth', 'sixty'],
  70: ['seventieth', 'seventy'],
  80: ['eightieth', 'eighty'],
  90: ['ninetieth', 'ninety'],
  100: ['hundredth', 'hundred'],
  levels: [
    ['', ''],
    ['thousandth', 'thousand'],
    ['millionth', 'million'],
    ['billionth', 'billion'],
    ['trillionth', 'trillion'],
  ],
};

export default EN;
