//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDAP_TEST {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageSettings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDAP_TEST.LanguageSettings", typeof(LanguageSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  billion.
        /// </summary>
        internal static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на th.
        /// </summary>
        internal static string eding0 {
            get {
                return ResourceManager.GetString("eding0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на y.
        /// </summary>
        internal static string eding1 {
            get {
                return ResourceManager.GetString("eding1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ieth.
        /// </summary>
        internal static string eding2 {
            get {
                return ResourceManager.GetString("eding2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  eigh.
        /// </summary>
        internal static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  eighteen.
        /// </summary>
        internal static string eighteen {
            get {
                return ResourceManager.GetString("eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  eight.
        /// </summary>
        internal static string eighty {
            get {
                return ResourceManager.GetString("eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  eleven.
        /// </summary>
        internal static string eleven {
            get {
                return ResourceManager.GetString("eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fifteen.
        /// </summary>
        internal static string fifteen {
            get {
                return ResourceManager.GetString("fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fifth.
        /// </summary>
        internal static string fifth {
            get {
                return ResourceManager.GetString("fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fift.
        /// </summary>
        internal static string fifty {
            get {
                return ResourceManager.GetString("fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  first.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  five.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fort.
        /// </summary>
        internal static string forty {
            get {
                return ResourceManager.GetString("forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  four.
        /// </summary>
        internal static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fourteen.
        /// </summary>
        internal static string fourteen {
            get {
                return ResourceManager.GetString("fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  fourth.
        /// </summary>
        internal static string fourth {
            get {
                return ResourceManager.GetString("fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  hundred.
        /// </summary>
        internal static string hundred {
            get {
                return ResourceManager.GetString("hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save changes and restart program?.
        /// </summary>
        internal static string messageBoxConfirmText {
            get {
                return ResourceManager.GetString("messageBoxConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string messageBoxConfirmTitle {
            get {
                return ResourceManager.GetString("messageBoxConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Еnter value.
        /// </summary>
        internal static string messageBoxErrText {
            get {
                return ResourceManager.GetString("messageBoxErrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string messageBoxErrTitle {
            get {
                return ResourceManager.GetString("messageBoxErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  million.
        /// </summary>
        internal static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  nine.
        /// </summary>
        internal static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  nineteen.
        /// </summary>
        internal static string nineteen {
            get {
                return ResourceManager.GetString("nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ninet.
        /// </summary>
        internal static string ninety {
            get {
                return ResourceManager.GetString("ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  one.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  seven.
        /// </summary>
        internal static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  seventeen.
        /// </summary>
        internal static string seventeen {
            get {
                return ResourceManager.GetString("seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  sevent.
        /// </summary>
        internal static string seventy {
            get {
                return ResourceManager.GetString("seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  six.
        /// </summary>
        internal static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  sixteen.
        /// </summary>
        internal static string sixteen {
            get {
                return ResourceManager.GetString("sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  sixt.
        /// </summary>
        internal static string sixty {
            get {
                return ResourceManager.GetString("sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ten.
        /// </summary>
        internal static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  third.
        /// </summary>
        internal static string third {
            get {
                return ResourceManager.GetString("third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  thirteen.
        /// </summary>
        internal static string thirteen {
            get {
                return ResourceManager.GetString("thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  thirt.
        /// </summary>
        internal static string thirty {
            get {
                return ResourceManager.GetString("thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  thousand.
        /// </summary>
        internal static string thousand {
            get {
                return ResourceManager.GetString("thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  three.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  trillion.
        /// </summary>
        internal static string trillion {
            get {
                return ResourceManager.GetString("trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  twelve.
        /// </summary>
        internal static string twelve {
            get {
                return ResourceManager.GetString("twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  twent.
        /// </summary>
        internal static string twenty {
            get {
                return ResourceManager.GetString("twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  two.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zero.
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
